name: Metabill
description: A new Flutter project.

orientation:

  android:

    portrait:
      enabled: true

    landscape:
      enabled: true

  ios:

    general:
      enabled: true

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #  flutter_localizations:
  #    sdk: flutter

  # firebase:
  #  firebase_core: ^1.6.0
  #  firebase_auth: ^4.4.2
  #  firebase_core_platform_interface: 4.6.0
  #  google_mlkit_text_recognition: ^0.5.0
  #  google_ml_kit: ^0.13.0
  # tflite: ^1.1.2

  #  firebase_core: ^1.6.0
  #  firebase_ml_vision: ^0.11.0

  intl: ^0.17.0

  #cupertino_icons: ^1.0.2
  provider: ^6.0.3


  # network request:
  http: ^0.13.4
  dio: ^5.1.2
  connectivity_plus: ^3.0.3

  #push_notification:
  onesignal_flutter: ^3.5.0


  #local database:
  #  sqflite: ^2.2.5
  #  floor: ^1.4.0
  #  objectbox: ^1.7.2


  # decore
  fluttertoast: ^8.0.8
  shimmer: ^2.0.0
  lottie: ^2.3.0
  flutter_svg: ^2.0.5


  #database:
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.1


  #obfuscate
  flutter_dotenv: ^5.0.2


  #services:
  image_picker: ^0.8.3+2
  path_provider: ^2.0.14
  uuid: ^4.2.1
  open_filex: ^4.3.2
  #  simple_barcode_scanner: ^0.0.8


  #helpers:
  device_info_plus: ^8.2.0
  package_info_plus: ^3.1.0
  open_settings: ^2.0.2
  faker: ^2.1.0
  url_launcher: ^6.1.10
  focus_detector: ^2.0.1
  pdf_render: ^1.4.0
  flutter_cache_manager: ^3.3.0
  permission_handler: ^10.4.3
  async: ^2.10.0


  #widgets:
  syncfusion_flutter_charts: ^19.3.61
  dropdown_search: ^5.0.6
  webview_flutter: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  floor_generator: ^1.4.1
  build_runner: ^2.1.2


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/locale.json
#    - assets/png/
#    - assets/svg/
#    - assets/lottie/
#    - assets/test/
#    - assets/sounds/
#    - .env

#  fonts:
#    - family: opensansreg
#      fonts:
#        - asset: assets/fonts/opensansreg.ttf
#    - family: rubikreg
#      fonts:
#        - asset: assets/fonts/rubikreg.ttf
#    - family: nutinoreg
#      fonts:
#        - asset: assets/fonts/nutinoreg.ttf
#    - family: lato
#      fonts:
#        - asset: assets/fonts/latoreg.ttf
##    - family: sourcesans
##      fonts:
##        - asset: assets/fonts/SourceSansReg.ttf

